# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09a7774a36e28827acd717ea6b4c200e0713254f9ae3dc890aaf9fc7cdc5c7a56c29556b310b33dbf1ffb45db925ef18da92f29279a1482901a493da6166775f

test:
  secret_key_base: 28a576408f45a1e22647c02210e9e0f9668e95b1c5e7313dcb72bfc1d404c039a9bb12c63c4746834e5008acbd88f59dcf46f8e991a6d1ee8a109e0fdf568745

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
